---
version: 0.2

env:
  variables: {}
  parameter-store: {}

phases:
  install:
    commands:
      # Install prerequisite packages
      - yum install -y wget rpm-build rpmdevtools redhat-rpm-config gcc git libffi-devel openssl-devel readline-devel zlib-devel bzip2 aws-cli

  pre_build:
    commands:
      # Prepare rpmbuild environment
      - rpmdev-setuptree
      - echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
      - cp rpm/xe_mirror.spec ~/rpmbuild/SPECS

      # Download Ruby source using spectool
      - cd ~/rpmbuild/SOURCES
      - spectool -g ~/rpmbuild/SPECS/xe_mirror.spec

  build:
    commands:
      # Build RPM
      - cd ~/rpmbuild/SPECS
      - rpmbuild -v -bb xe_mirror.spec

  post_build:
    commands:
      # Check RPM dependencies
      - rpm -qRp /root/rpmbuild/RPMS/x86_64/*.rpm

      # Test RPM installation
      - yum install -y /root/rpmbuild/RPMS/x86_64/*.rpm
      - ls -l /opt/xe_mirror
      - ls -l /home/mirror/.ssh

      # Upload the artifacts
      - aws s3 cp /root/rpmbuild/RPMS/x86_64/xe_mirror-2.0-1.amzn1.x86_64.rpm s3://r.sigcorp.com/xe_mirror/
      - aws s3 cp ${CODEBUILD_SRC_DIR}/ellucian_git_mirror.rb s3://r.sigcorp.com/xe_mirror/

artifacts:
  files: []
    # - ellucian_git_mirror.rb
    # - /root/rpmbuild/RPMS/x86_64/*.rpm
  discard-paths: yes
