# -*- mode: ruby -*-
# vi: set ft=ruby :

# If you have errors with vboxfs:
# vagrant plugin install vagrant-vbguest
# vagrant reload
#
# If this doesn't work, to manually install guest additions:
# sudo su -
# yum update -y kernel*  # REBOOT IF UPDATES APPLIED
# rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#
# To determine IP address: ip a
#
# Example config:
#
# external_url 'http://172.16.16.207'
# gitlab_rails['gitlab_ssh_host'] = '172.16.16.207'
#
# To use the dev version:
# sudo ln -sf /mnt/code/ellucian_git_mirror.rb /opt/xe_mirror/ellucian_git_mirror.rb

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.synced_folder "..", "/mnt/code"

  # View the documentation for the provider you are using for more
  # information on available options.

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
