name: main

on:
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ban-git-mirror:latest


      - name: Docker Hub Login
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag ban-git-mirror:latest sigcorp/ban-git-mirror:latest || exit 1
          docker tag ban-git-mirror:latest sigcorp/ban-git-mirror:r${{ github.run_number }} || exit 1
          docker push sigcorp/ban-git-mirror:latest || exit 1
          docker push sigcorp/ban-git-mirror:r${{ github.run_number }} || exit 1
